// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RhInteligenteDbContext))]
    partial class RhInteligenteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AlertaAnomalia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DataReferencia")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Gravidade")
                        .HasColumnType("integer");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoAnomalia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "FuncionarioId", "DataReferencia")
                        .HasDatabaseName("IX_AlertasAnomalia_EmpresaId_FuncionarioId_DataRef");

                    b.HasIndex("EmpresaId", "Resolvido", "Gravidade")
                        .HasDatabaseName("IX_AlertasAnomalia_EmpresaId_Resolvido_Gravidade");

                    b.ToTable("AlertasAnomalia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Funcionario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDemissao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Funcionarios_EmpresaId_Cpf");

                    b.HasIndex("EmpresaId", "Matricula")
                        .IsUnique()
                        .HasDatabaseName("IX_Funcionarios_EmpresaId_Matricula");

                    b.ToTable("Funcionarios", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RegistroPonto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataHoraBatida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FuncionarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justificativa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("LancamentoManual")
                        .HasColumnType("boolean");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TipoBatida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("EmpresaId", "FuncionarioId", "DataHoraBatida")
                        .HasDatabaseName("IX_RegistrosPonto_EmpresaId_FuncionarioId_DataHora");

                    b.ToTable("RegistrosPonto", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Funcionario", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.TurnoTrabalho", "TurnoContratual", b1 =>
                        {
                            b1.Property<Guid>("FuncionarioId")
                                .HasColumnType("uuid");

                            b1.Property<TimeSpan>("DuracaoIntervalo")
                                .HasColumnType("interval")
                                .HasColumnName("TurnoDuracaoIntervalo");

                            b1.Property<TimeOnly>("HoraEntrada")
                                .HasColumnType("time without time zone")
                                .HasColumnName("TurnoHoraEntrada");

                            b1.Property<TimeOnly>("HoraSaida")
                                .HasColumnType("time without time zone")
                                .HasColumnName("TurnoHoraSaida");

                            b1.HasKey("FuncionarioId");

                            b1.ToTable("Funcionarios");

                            b1.WithOwner()
                                .HasForeignKey("FuncionarioId");
                        });

                    b.Navigation("TurnoContratual")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.RegistroPonto", b =>
                {
                    b.HasOne("Domain.Entities.Funcionario", null)
                        .WithMany("RegistrosPonto")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Funcionario", b =>
                {
                    b.Navigation("RegistrosPonto");
                });
#pragma warning restore 612, 618
        }
    }
}
